{
 "title": "BentoML Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "request_in_progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "BENTOML_sklearn:elastic:net:reg_request_in_progress{endpoint=\"/inference\"}"
    }
   ]
  },
  {
   "title": "mb_request_duration",
   "type": "graph",
   "description": "microbatch request duration seconds",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.85, sum by(le) (rate(BENTOML_sklearn:elastic:net:reg_request_duration_seconds_bucket{endpoint=\"/inference\"}[5m])))"
    }
   ]
  },
  {
   "title": "mb_request_total",
   "type": "graph",
   "description": "microbatch request total",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(BENTOML_sklearn:elastic:net:reg_request_total{endpoint=\"/inference\"}[5m])"
    }
   ]
  },
  {
   "title": "request_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(BENTOML_sklearn:elastic:net:reg_request_total{endpoint=\"/inference\"}[5m])"
    }
   ]
  }
 ]
}