version: "3"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181

    broker:
        image: confluentinc/cp-kafka:7.0.1
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    kafka_events:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            BOOTSTRAP_SERVERS: localhost:29092
            DATA: data/driver_stats_stream.parquet
        depends_on:
            - broker
        network_mode: "host"
