version: "3.7"
services:
  bentoml_service:
    image: $DOCKER_USER/mlops_crash_course/model_serving:latest
    container_name: online_serving
    restart: on-failure
    volumes:
      - ../artifacts:/model_serving/artifacts
      - ../feature_repo:/model_serving/feature_repo
    command: /bin/bash scripts/bentoml_helper.sh serve --port=$ONLINE_SERVING_PORT
    ports:
      - $ONLINE_SERVING_PORT:$ONLINE_SERVING_PORT
