PUSH_IMAGE=""
DAGS_DIR="../../mlops-crash-course-platform/airflow/run_env/dags/"

update_image:
	bash deployment/update_image.sh "${PUSH_IMAGE}"

deploy_dags:
	bash deployment/deploy_dags.sh "${DAGS_DIR}"
